server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: udxAtugEqSu@6bP
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    default-schema: public

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

